language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t narasimhaconnect/react-test -f ./client/Dockerfile/dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t narasimhaconnect/multi-client ./client
  - docker build -t narasimhaconnect/multi-server ./server
  - docker build -t narasimhaconnect/multi-worker ./worker
  - docker build -t narasimhaconnect/multi-nginx ./nginx
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push narasimhaconnect/multi-client
  - docker push narasimhaconnect/multi-server
  - docker push narasimhaconnect/multi-worker
  - docker push narasimhaconnect/multi-nginx
